name: AntiMobSpawn
version: 2.0
main: uk.samlex.antimobspawn.AntiMobSpawn
author: Sam_lex
description: Allows the user to select a number of options to do with stopping creatures spawning. The user can choose which creatures not to spawn, which block types they can't spawn on and areas where they can't spawn. All options can be set per world as well!
