name: AntiMobSpawn
version: 3.0
main: uk.samlex.antimobspawn.AntiMobSpawn
author: Sam_lex
description: A highly configurable creatrue spawn blocker
commands:
   ams:
     description: Reloads the configuration values from disk
     aliases: reloadams